name: Build APK với Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Giúp bấm nút tự kích hoạt build bằng tay bất cứ lúc nào

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout mã nguồn
      uses: actions/checkout@v4 # Đã nâng cấp lên v4

    - name: Cài đặt các công cụ hệ thống và Rust
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config patch unzip textinfo
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Thiết lập Cache cho Buildozer
      uses: actions/cache@v4 # Đã nâng cấp lên v4
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Chạy Buildozer đóng gói APK
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: master

    - name: Tải file APK lên Artifacts để download
      uses: actions/upload-artifact@v4 # Sửa triệt để lỗi ép buộc v4 của GitHub
      with:
        name: Buildozer-APK
        path: bin/*.apk
        
